-- Change columns
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN BUSINESS_APPLICATION_PARAMS;
ALTER TABLE CPF.CPF_BATCH_JOBS ADD BUSINESS_APPLICATION_PARAMS CLOB;
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN PROPERTIES;
ALTER TABLE CPF.CPF_BATCH_JOBS ADD PROPERTIES CLOB;
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY STRUCTURED_INPUT_DATA_URL VARCHAR2(2000);
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY NUM_SUBMITTED_REQUESTS NUMBER(19) NOT NULL;
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY NUM_SUBMITTED_GROUPS NUMBER(19) NOT NULL;

-- New columns
ALTER TABLE CPF.CPF_BATCH_JOBS ADD COMPLETED_REQUEST_RANGE CLOB;
COMMENT ON COLUMN CPF_BATCH_JOBS.COMPLETED_REQUEST_RANGE IS 'This is the range of requests which have been completed successfully for the BATCH JOB.';

ALTER TABLE CPF.CPF_BATCH_JOBS ADD COMPLETED_GROUP_RANGE CLOB;
COMMENT ON COLUMN CPF_BATCH_JOBS.COMPLETED_GROUP_RANGE IS 'This is the range of groups which have been completed successfully for the BATCH JOB.';

ALTER TABLE CPF.CPF_BATCH_JOBS ADD FAILED_REQUEST_RANGE CLOB;
COMMENT ON COLUMN CPF_BATCH_JOBS.FAILED_REQUEST_RANGE IS 'This is the range of requests which failed to be completed for the BATCH JOB.';

ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN STRUCTURED_INPUT_DATA;
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN NUM_COMPLETED_GROUPS;
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN NUM_SCHEDULED_GROUPS;
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN NUM_COMPLETED_REQUESTS;
ALTER TABLE CPF.CPF_BATCH_JOBS DROP COLUMN NUM_FAILED_REQUESTS;
