-- 4.2.0
-- CPF_BATCH_JOB_RESULTS
ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS DROP COLUMN BATCH_JOB_EXECUTION_GROUP_ID
/

UPDATE CPF.CPF_BATCH_JOB_RESULTS SET SEQUENCE_NUMBER = 1 where BATCH_JOB_RESULT_TYPE = 'structuredResultData';
UPDATE CPF.CPF_BATCH_JOB_RESULTS SET SEQUENCE_NUMBER = 0 where BATCH_JOB_RESULT_TYPE = 'errorResultData';

ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS DROP CONSTRAINT CPF_BJRS_PK
/

ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS DROP COLUMN batch_result_id
/
ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS ALTER SEQUENCE_NUMBER NUMBER(19,0) NOT NULL
/

ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS ADD CONSTRAINT CPF_BJRS_PK PRIMARY KEY (BATCH_JOB_ID, SEQUENCE_NUMBER)
/

DROP SEQUENCE cpf.cpf_bjrs_seq
/

-- CPF_BATCH_JOB_EXECUTION_GROUPS

ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP CONSTRAINT CPF_BJEG_PK
/

ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN batch_job_execution_group_id
/

ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN batch_result_id
/

ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS ADD CONSTRAINT CPF_BJEG_PK PRIMARY KEY (BATCH_JOB_ID, SEQUENCE_NUMBER)
/

DROP SEQUENCE cpf.cpf_bjeg_seq
/

CREATE TABLE CPF_BATCH_JOB_FILES
 (BATCH_JOB_ID NUMBER(19,0) NOT NULL
 ,PATH VARCHAR2(20) NOT NULL
 ,SEQUENCE_NUMBER NUMBER(19,0)
 ,DATA BLOB
 ,CONTENT_TYPE VARCHAR2(50)
 )
 TABLESPACE CPF
/

ALTER TABLE CPF.CPF_BATCH_JOB_FILES ADD CONSTRAINT CPF_BJF_PK PRIMARY KEY (BATCH_JOB_ID, PATH, SEQUENCE_NUMBER)
/

ALTER TABLE CPF.CPF_BATCH_JOB_FILES ADD CONSTRAINT
 CPF_BJF_CPF_BJ_FK FOREIGN KEY 
  (BATCH_JOB_ID) REFERENCES CPF_BATCH_JOBS
  (BATCH_JOB_ID)
/

CREATE INDEX CPF_BJF_CPF_BJ_FK_I ON CPF.CPF_BATCH_JOB_FILES
 (BATCH_JOB_ID)
 TABLESPACE CPF_NDX
/

