
ALTER TABLE CPF.CPF_USER_GROUP_ACCOUNT_XREF ADD WHO_CREATED                     VARCHAR2(255);
ALTER TABLE CPF.CPF_USER_GROUP_ACCOUNT_XREF ADD WHEN_CREATED                    TIMESTAMP;

UPDATE CPF.CPF_USER_GROUP_ACCOUNT_XREF SET WHO_CREATED='SYSTEM', WHEN_CREATED = SYSDATE;

ALTER TABLE CPF.CPF_USER_GROUP_ACCOUNT_XREF MODIFY WHO_CREATED                     VARCHAR2(255) NOT NULL;
ALTER TABLE CPF.CPF_USER_GROUP_ACCOUNT_XREF MODIFY WHEN_CREATED                    TIMESTAMP NOT NULL;

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.WHO_CREATED IS 'This is the database or web user that created the object.';

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.WHEN_CREATED IS 'This is the date that the object was created.';
