CREATE TABLE CPF_BATCH_JOB_STATUS_CHANGE (
  BATCH_JOB_STATUS_CHANGE_ID      NUMBER(19)          NOT NULL,
  BATCH_JOB_ID                    NUMBER(19)          NOT NULL,
  JOB_STATUS                      VARCHAR2(50)     NOT NULL,
  WHO_CREATED                     VARCHAR2(255)    NOT NULL,
  WHEN_CREATED                    TIMESTAMP       NOT NULL,
  
  CONSTRAINT BATCH_JOB_STATUS_CHANGE_PK PRIMARY KEY (BATCH_JOB_STATUS_CHANGE_ID),

  CONSTRAINT BATCH_JOB_STATUS_CHANGE_FK FOREIGN KEY (BATCH_JOB_ID) REFERENCES CPF.CPF_BATCH_JOBS(BATCH_JOB_ID) ON DELETE CASCADE
);

CREATE INDEX CPF_BJSC_BJ_FK_I ON CPF.CPF_BATCH_JOB_STATUS_CHANGE (BATCH_JOB_ID);

-- Sequence

CREATE SEQUENCE CPF_BJSC_SEQ;

-- Grants

GRANT DELETE, INSERT, SELECT, UPDATE ON CPF_BATCH_JOB_STATUS_CHANGE TO CPF_USER;

GRANT SELECT ON CPF_BATCH_JOB_STATUS_CHANGE TO CPF_VIEWER;

GRANT SELECT ON CPF_BJSC_SEQ TO CPF_USER;

-- Comments

COMMENT ON TABLE CPF_BATCH_JOB_STATUS_CHANGE IS 'The BATCH JOB STATUS CHANGE is used to record each status change for a BATCH JOB.';

COMMENT ON COLUMN CPF_BATCH_JOB_STATUS_CHANGE.BATCH_JOB_STATUS_CHANGE_ID IS 'This is the unique key for the BATCH JOB STATUS CHANGE.';

COMMENT ON COLUMN CPF_BATCH_JOB_STATUS_CHANGE.JOB_STATUS IS 'This is the status of the job (submitted, creatingRequests, processing, processed, creatingResults, resultsGenerated, downloadInitiated, deleteInitiated, cancelled).';

COMMENT ON COLUMN CPF_BATCH_JOB_STATUS_CHANGE.BATCH_JOB_ID IS 'This is the unique key for the BATCH JOB.';

COMMENT ON COLUMN CPF_BATCH_JOB_STATUS_CHANGE.WHO_CREATED IS 'This is the database or web user that created the object.';

COMMENT ON COLUMN CPF_BATCH_JOB_STATUS_CHANGE.WHEN_CREATED IS 'This is the date that the object was created.';
