CREATE TABLE CPF_USER_GROUP_ACCOUNT_XREF (
  USER_ACCOUNT_ID                 NUMBER(19)          NOT NULL,
  USER_GROUP_ID                   NUMBER(19)          NOT NULL,
  WHO_CREATED                     VARCHAR2(255)    NOT NULL,
  WHEN_CREATED                    TIMESTAMP       NOT NULL,
  
  CONSTRAINT USER_GROUP_ACCOUNT_XREF_PK PRIMARY KEY (USER_GROUP_ID, USER_ACCOUNT_ID),
  
  CONSTRAINT CPF_UGAX_UA_FK FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES CPF.CPF_USER_ACCOUNTS(USER_ACCOUNT_ID),
  CONSTRAINT CPF_UGAX_UG_FK FOREIGN KEY (USER_GROUP_ID) REFERENCES CPF.CPF_USER_GROUPS(USER_GROUP_ID)
);

CREATE INDEX CPF_UGAX_UA_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF (USER_ACCOUNT_ID);

CREATE INDEX CPF_UGAX_UG_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF (USER_GROUP_ID);

-- Grants

GRANT DELETE, INSERT, SELECT, UPDATE ON CPF_USER_GROUP_ACCOUNT_XREF TO CPF_USER;

-- Comments

COMMENT ON TABLE CPF_USER_GROUP_ACCOUNT_XREF IS 'USER GROUP ACCOUNT XREF represents a relationship between a USER GROUP and the USER ACCOUNT that is a member of that group.';

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.USER_GROUP_ID IS 'USER GROUP ID is a unique surrogate identifier for the object USER GROUP.';

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.USER_ACCOUNT_ID IS 'USER ACCOUNT ID is a unique surrogate identifier for the object USER ACCOUNT.';

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.WHO_CREATED IS 'This is the database or web user that created the object.';

COMMENT ON COLUMN CPF_USER_GROUP_ACCOUNT_XREF.WHEN_CREATED IS 'This is the date that the object was created.';

