UPDATE CPF.CPF_BATCH_JOBS SET JOB_STATUS = 'cancelled' WHERE JOB_STATUS NOT IN ('creatingResults', 'resultsCreated', 'downloadInitiated');

ALTER TABLE CPF.CPF_BATCH_JOBS RENAME COLUMN NUM_EXECUTING_REQUESTS TO NUM_SCHEDULED_GROUPS;
ALTER TABLE CPF.CPF_BATCH_JOBS ADD GROUP_SIZE NUMBER(5,0);
ALTER TABLE CPF.CPF_BATCH_JOBS ADD NUM_SUBMITTED_GROUPS NUMBER(19,0);
ALTER TABLE CPF.CPF_BATCH_JOBS ADD NUM_COMPLETED_GROUPS NUMBER(19,0);
UPDATE CPF.CPF_BATCH_JOBS SET GROUP_SIZE = 0, NUM_SUBMITTED_GROUPS = 0, NUM_COMPLETED_GROUPS = 0;
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY GROUP_SIZE NUMBER(5,0) NOT NULL;
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY NUM_SUBMITTED_GROUPS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF.CPF_BATCH_JOBS MODIFY NUM_COMPLETED_GROUPS NUMBER(19,0) NOT NULL;

ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS DROP COLUMN ERROR_CODE;
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS DROP COLUMN ERROR_DEBUG_MESSAGE;
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS DROP COLUMN ERROR_MESSAGE;

ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS ADD NUM_SUBMITTED_REQUESTS NUMBER(19,0);
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS ADD NUM_COMPLETED_REQUESTS NUMBER(19,0);
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS ADD NUM_FAILED_REQUESTS NUMBER(19,0);
UPDATE CPF.CPF_BATCH_JOB_REQUESTS SET NUM_SUBMITTED_REQUESTS = 0,  NUM_COMPLETED_REQUESTS = 0,  NUM_FAILED_REQUESTS = 0;
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS MODIFY NUM_SUBMITTED_REQUESTS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS MODIFY NUM_COMPLETED_REQUESTS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF.CPF_BATCH_JOB_REQUESTS MODIFY NUM_FAILED_REQUESTS NUMBER(19,0) NOT NULL;
