UPDATE CPF_BATCH_JOBS SET JOB_STATUS = 'cancelled' WHERE JOB_STATUS NOT IN ('creatingResults', 'resultsCreated', 'downloadInitiated');
COMMIT;
ALTER TABLE CPF_BATCH_JOBS RENAME COLUMN NUM_EXECUTING_REQUESTS TO NUM_SCHEDULED_GROUPS;
ALTER TABLE CPF_BATCH_JOBS ADD GROUP_SIZE NUMBER(5,0);
ALTER TABLE CPF_BATCH_JOBS ADD NUM_SUBMITTED_GROUPS NUMBER(19,0);
ALTER TABLE CPF_BATCH_JOBS ADD NUM_COMPLETED_GROUPS NUMBER(19,0);
UPDATE CPF_BATCH_JOBS SET GROUP_SIZE = 0, NUM_SUBMITTED_GROUPS = 0, NUM_COMPLETED_GROUPS = 0;
COMMIT;
ALTER TABLE CPF_BATCH_JOBS MODIFY GROUP_SIZE NUMBER(5,0) NOT NULL;
ALTER TABLE CPF_BATCH_JOBS MODIFY NUM_SUBMITTED_GROUPS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF_BATCH_JOBS MODIFY NUM_COMPLETED_GROUPS NUMBER(19,0) NOT NULL;

ALTER TABLE CPF_BATCH_JOB_REQUESTS RENAME TO CPF_BATCH_JOB_EXECUTION_GROUPS;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN ERROR_CODE;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN ERROR_DEBUG_MESSAGE;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN ERROR_MESSAGE;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS ADD NUM_SUBMITTED_REQUESTS NUMBER(19,0);
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS ADD NUM_COMPLETED_REQUESTS NUMBER(19,0);
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS ADD NUM_FAILED_REQUESTS NUMBER(19,0);
UPDATE CPF_BATCH_JOB_EXECUTION_GROUPS SET NUM_SUBMITTED_REQUESTS = 0,  NUM_COMPLETED_REQUESTS = 0,  NUM_FAILED_REQUESTS = 0;
COMMIT;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS MODIFY NUM_SUBMITTED_REQUESTS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS MODIFY NUM_COMPLETED_REQUESTS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS MODIFY NUM_FAILED_REQUESTS NUMBER(19,0) NOT NULL;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS RENAME COLUMN BATCH_JOB_REQUEST_ID TO BATCH_JOB_EXECUTION_GROUP_ID;
ALTER TABLE CPF_BATCH_JOB_EXECUTION_GROUPS RENAME COLUMN REQUEST_SEQUENCE_NUMBER TO SEQUENCE_NUMBER;

ALTER TABLE CPF_BATCH_JOB_RESULTS RENAME COLUMN BATCH_JOB_REQUEST_ID TO BATCH_JOB_EXECUTION_GROUP_ID;
ALTER TABLE CPF_BATCH_JOB_RESULTS RENAME COLUMN REQUEST_SEQUENCE_NUMBER TO SEQUENCE_NUMBER;

RENAME CPF_BJRQ_SEQ TO CPF_BJEG_SEQ;