CREATE TABLE CPF_BATCH_JOB_STATUS_CHANGE (
  BATCH_JOB_STATUS_CHANGE_ID      BIGINT                      NOT NULL,
  BATCH_JOB_ID                    BIGINT                      NOT NULL,
  JOB_STATUS                      CHARACTER VARYING(50)       NOT NULL,
  WHO_CREATED                     CHARACTER VARYING(36)       NOT NULL,
  WHEN_CREATED                    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  
  CONSTRAINT BATCH_JOB_STATUS_CHANGE_PK PRIMARY KEY (BATCH_JOB_STATUS_CHANGE_ID),
  CONSTRAINT BATCH_JOB_STATUS_CHANGE_FK FOREIGN KEY (BATCH_JOB_ID) REFERENCES CPF.CPF_BATCH_JOBS(BATCH_JOB_ID) ON DELETE CASCADE
);

CREATE INDEX CPF_BJSC_BJ_FK_I ON CPF.CPF_BATCH_JOB_STATUS_CHANGE (BATCH_JOB_ID);

CREATE SEQUENCE CPF_BJSC_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
