CREATE TABLE CPF_BATCH_JOBS (
  BATCH_JOB_ID                    BIGINT NOT NULL,
  USER_ID                         CHARACTER VARYING(50) NOT NULL,
  BUSINESS_APPLICATION_NAME       CHARACTER VARYING(255) NOT NULL,
  BUSINESS_APPLICATION_PARAMS     TEXT,
  PROPERTIES                      TEXT,
  WHEN_STATUS_CHANGED             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  COMPLETED_TIMESTAMP             TIMESTAMP WITHOUT TIME ZONE,
  INPUT_DATA_CONTENT_TYPE         CHARACTER VARYING(255),
  STRUCTURED_INPUT_DATA_URL       CHARACTER VARYING(2000),
  JOB_STATUS CHARACTER            VARYING(50) NOT NULL,
  LAST_SCHEDULED_TIMESTAMP        TIMESTAMP WITHOUT TIME ZONE,
  NOTIFICATION_URL                CHARACTER VARYING(2000),
  COMPLETED_REQUEST_RANGE         TEXT,
  COMPLETED_GROUP_RANGE           TEXT,
  FAILED_REQUEST_RANGE            TEXT,
  NUM_SUBMITTED_REQUESTS          INTEGER NOT NULL,
  RESULT_DATA_CONTENT_TYPE        CHARACTER VARYING(255) NOT NULL,
  WHO_CREATED                     CHARACTER VARYING(36) NOT NULL,
  WHEN_CREATED                    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  WHO_UPDATED                     CHARACTER VARYING(36) NOT NULL,
  WHEN_UPDATED                    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  NUM_SUBMITTED_GROUPS            INTEGER NOT NULL,
  GROUP_SIZE                      SMALLINT NOT NULL,
  
  CONSTRAINT BATCH_JOBS_PK PRIMARY KEY (BATCH_JOB_ID)
);

CREATE INDEX BATCH_JOBS_STATUS_APP_IDX ON CPF.CPF_BATCH_JOBS (JOB_STATUS, BUSINESS_APPLICATION_NAME);

CREATE SEQUENCE CPF_BJ_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
