GRANT USAGE ON SCHEMA CPF TO GROUP CPF_VIEWER;

GRANT SELECT ON ALL TABLES IN SCHEMA CPF TO GROUP CPF_VIEWER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CPF TO GROUP CPF_USER;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA CPF TO GROUP CPF_USER;


