 

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BJRS_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_CP_SEQ TO CPF_USER;

GRANT SELECT ON CPF_AS_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BJRQ_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_UG_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_UA_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_UGP_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BJ_SEQ TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_USER_GROUP_PERMISSIONS TO CPF_USER;

GRANT SELECT ON CPF_CONFIG_PROPERTIES TO CPF_VIEWER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_CONFIG_PROPERTIES TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BATCH_JOBS TO CPF_USER;

GRANT SELECT ON CPF_BATCH_JOBS TO CPF_VIEWER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BATCH_JOB_RESULTS TO CPF_USER;

GRANT SELECT ON CPF_BATCH_JOB_RESULTS TO CPF_VIEWER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_BATCH_JOB_REQUESTS TO CPF_USER;

GRANT SELECT ON CPF_BATCH_JOB_REQUESTS TO CPF_VIEWER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_USER_ACCOUNTS TO CPF_USER;

GRANT SELECT ON CPF_APPLICATION_STATISTICS TO CPF_VIEWER;

GRANT DELETE, INSERT, SELECT, UPDATE ON CPF_APPLICATION_STATISTICS TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_USER_GROUP_ACCOUNT_XREF TO CPF_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON CPF_USER_GROUPS TO CPF_USER;


