  

CREATE INDEX CPF_UGP_CPF_UG_FK_I ON CPF.CPF_USER_GROUP_PERMISSIONS
 (USER_GROUP_ID);

CREATE INDEX CPF_BJRS_CPF_BJ_FK_I ON CPF.CPF_BATCH_JOB_RESULTS
 (BATCH_JOB_ID);

CREATE INDEX CPF_BJRQ_CPF_BJ_FK_I ON CPF.CPF_BATCH_JOB_REQUESTS
 (BATCH_JOB_ID);

CREATE INDEX CPF_BJRQ_BJ_ID_STARTED_I ON CPF.CPF_BATCH_JOB_REQUESTS
 (BATCH_JOB_ID
 ,STARTED_IND);

CREATE INDEX CPF_BJ_STATUS_APP_NAME_I ON CPF.CPF_BATCH_JOBS
 (BUSINESS_APPLICATION_NAME
 ,JOB_STATUS);

CREATE INDEX CPF_UGAX_CPF_UG_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF
 (USER_GROUP_ID);

CREATE INDEX CPF_UGAX_CPF_UA_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF
 (USER_ACCOUNT_ID);


