CREATE SCHEMA CPF;
 


CREATE TABLE CPF.CPF_USER_GROUP_PERMISSIONS
 (USER_GROUP_PERMISSION_ID NUMERIC(19,0) NOT NULL
 ,MODULE_NAME VARCHAR(255) NOT NULL
 ,USER_GROUP_ID NUMERIC(19) NOT NULL
 ,RESOURCE_CLASS VARCHAR(255) NOT NULL
 ,RESOURCE_ID VARCHAR(4000) NOT NULL
 ,ACTION_NAME VARCHAR(255) NOT NULL
 ,ACTIVE_IND NUMERIC(1,0) NOT NULL
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_BATCH_JOB_RESULTS
 (BATCH_JOB_RESULT_ID NUMERIC(19,0) NOT NULL
 ,BATCH_JOB_ID NUMERIC(19,0) NOT NULL
 ,BATCH_JOB_RESULT_TYPE VARCHAR(50) NOT NULL
 ,RESULT_DATA_CONTENT_TYPE VARCHAR(255) NOT NULL
 ,BATCH_JOB_EXECUTION_GROUP_ID NUMERIC(19,0)
 ,DOWNLOAD_TIMESTAMP TIMESTAMP
 ,SEQUENCE_NUMBER NUMERIC(19,0)
 ,RESULT_DATA OID
 ,RESULT_DATA_URL VARCHAR(2000)
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS
 (BATCH_JOB_EXECUTION_GROUP_ID NUMERIC(19,0) NOT NULL
 ,BATCH_JOB_ID NUMERIC(19,0) NOT NULL
 ,BATCH_JOB_RESULT_ID NUMERIC(19,0)
 ,SEQUENCE_NUMBER NUMERIC(19,0) NOT NULL
 ,COMPLETED_IND NUMERIC(1,0) NOT NULL
 ,STARTED_IND NUMERIC(1,0) NOT NULL
 ,NUM_SUBMITTED_REQUESTS NUMERIC(19,0) NOT NULL
 ,NUM_COMPLETED_REQUESTS NUMERIC(19,0) NOT NULL
 ,NUM_FAILED_REQUESTS NUMERIC(19,0) NOT NULL
 ,INPUT_DATA OID
 ,INPUT_DATA_URL VARCHAR(2000)
 ,INPUT_DATA_CONTENT_TYPE VARCHAR(255)
 ,RESULT_DATA OID
 ,RESULT_DATA_URL VARCHAR(2000)
 ,STRUCTURED_INPUT_DATA TEXT
 ,STRUCTURED_RESULT_DATA TEXT
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_APPLICATION_STATISTICS
 (APPLICATION_STATISTIC_ID NUMERIC(19) NOT NULL
 ,BUSINESS_APPLICATION_NAME VARCHAR(255) NOT NULL
 ,START_TIMESTAMP DATE NOT NULL
 ,DURATION_TYPE VARCHAR(10) NOT NULL
 ,STATISTIC_VALUES VARCHAR(4000) NOT NULL
 );

CREATE TABLE CPF.CPF_BATCH_JOBS
 (BATCH_JOB_ID NUMERIC(19,0) NOT NULL
 ,BUSINESS_APPLICATION_NAME VARCHAR(255) NOT NULL
 ,JOB_STATUS VARCHAR(50) NOT NULL
 ,GROUP_SIZE NUMERIC(5,0) NOT NULL
 ,NUM_SUBMITTED_GROUPS NUMERIC(19,0) NOT NULL
 ,NUM_COMPLETED_GROUPS NUMERIC(19,0) NOT NULL
 ,NUM_SCHEDULED_GROUPS NUMERIC(19,0) NOT NULL
 ,NUM_COMPLETED_REQUESTS NUMERIC(19,0) NOT NULL
 ,NUM_FAILED_REQUESTS NUMERIC(19,0) NOT NULL
 ,NUM_SUBMITTED_REQUESTS NUMERIC(19,0) NOT NULL
 ,RESULT_DATA_CONTENT_TYPE VARCHAR(255) NOT NULL
 ,USER_ID VARCHAR(50) NOT NULL
 ,WHEN_STATUS_CHANGED TIMESTAMP NOT NULL
 ,BUSINESS_APPLICATION_PARAMS VARCHAR(4000)
 ,COMPLETED_TIMESTAMP TIMESTAMP
 ,STRUCTURED_INPUT_DATA OID
 ,STRUCTURED_INPUT_DATA_URL VARCHAR(255)
 ,INPUT_DATA_CONTENT_TYPE VARCHAR(255)
 ,LAST_SCHEDULED_TIMESTAMP TIMESTAMP
 ,NOTIFICATION_URL VARCHAR(2000)
 ,PROPERTIES VARCHAR(4000)
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_USER_GROUP_ACCOUNT_XREF
 (USER_GROUP_ID NUMERIC(19,0) NOT NULL
 ,USER_ACCOUNT_ID NUMERIC(19,0) NOT NULL
 );

CREATE TABLE CPF.CPF_USER_ACCOUNTS
 (USER_ACCOUNT_ID NUMERIC(19,0) NOT NULL
 ,USER_ACCOUNT_CLASS VARCHAR(255) NOT NULL
 ,USER_NAME VARCHAR(4000) NOT NULL
 ,CONSUMER_KEY VARCHAR(36) NOT NULL
 ,CONSUMER_SECRET VARCHAR(36) NOT NULL
 ,ACTIVE_IND NUMERIC(1,0) NOT NULL
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_CONFIG_PROPERTIES
 (CONFIG_PROPERTY_ID NUMERIC(19,0) NOT NULL
 ,ENVIRONMENT_NAME VARCHAR(255) NOT NULL
 ,MODULE_NAME VARCHAR(255) NOT NULL
 ,COMPONENT_NAME VARCHAR(255) NOT NULL
 ,PROPERTY_NAME VARCHAR(255) NOT NULL
 ,PROPERTY_VALUE_TYPE VARCHAR(255) NOT NULL
 ,PROPERTY_VALUE VARCHAR(4000)
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

CREATE TABLE CPF.CPF_USER_GROUPS
 (USER_GROUP_ID NUMERIC(19,0) NOT NULL
 ,MODULE_NAME VARCHAR(255) NOT NULL
 ,USER_GROUP_NAME VARCHAR(255) NOT NULL
 ,DESCRIPTION VARCHAR(4000)
 ,ACTIVE_IND NUMERIC(1,0) NOT NULL
 ,WHO_CREATED VARCHAR(36) NOT NULL
 ,WHEN_CREATED TIMESTAMP NOT NULL
 ,WHO_UPDATED VARCHAR(36) NOT NULL
 ,WHEN_UPDATED TIMESTAMP NOT NULL
 );

