CREATE TABLE CPF_USER_GROUP_ACCOUNT_XREF (
  USER_ACCOUNT_ID BIGINT NOT NULL,
  USER_GROUP_ID BIGINT NOT NULL,
  WHO_CREATED CHARACTER VARYING(255) NOT NULL,
  WHEN_CREATED TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  
  CONSTRAINT USER_GROUP_ACCOUNT_XREF_PK PRIMARY KEY (USER_GROUP_ID, USER_ACCOUNT_ID),
  CONSTRAINT CPF_UGAX_UA_FK FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES CPF.CPF_USER_ACCOUNTS(USER_ACCOUNT_ID),
  CONSTRAINT CPF_UGAX_UG_FK FOREIGN KEY (USER_GROUP_ID) REFERENCES CPF.CPF_USER_GROUPS(USER_GROUP_ID)
);


CREATE INDEX CPF_UGAX_UA_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF (USER_ACCOUNT_ID);

CREATE INDEX CPF_UGAX_UG_FK_I ON CPF.CPF_USER_GROUP_ACCOUNT_XREF (USER_GROUP_ID);
