PROMPT Creating Tablespace 'CPF' 
CREATE TABLESPACE CPF
DATAFILE '&CPF_TABLES_DIR/cpf_01.dbf' SIZE 1g
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT auto;

PROMPT Creating Tablespace 'CPF_NDX' 
CREATE TABLESPACE CPF_NDX  
DATAFILE '&CPF_INDEXES_DIR./cpf_ndx01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT auto;