PROMPT Creating Tablespace 'CPF_TABLES' 
CREATE TABLESPACE CPF_TABLES
DATAFILE '&CPF_TABLES_DIR/cpf_tables_01.dbf' SIZE 1g
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT auto;

PROMPT Creating Tablespace 'CPF_INDEXES' 
CREATE TABLESPACE CPF_INDEXES  
DATAFILE '&CPF_INDEXES_DIR./cpf_indexes_01.dbf' SIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT auto;