ALTER TABLE CPF.CPF_BATCH_JOB_RESULTS DROP COLUMN BATCH_JOB_EXECUTION_GROUP_ID;
ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP CONSTRAINT CPF_BJEG_PK;
ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN batch_job_execution_group_id;
ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS DROP COLUMN batch_result_id;
ALTER TABLE CPF.CPF_BATCH_JOB_EXECUTION_GROUPS ADD CONSTRAINT CPF_BJEG_PK PRIMARY KEY (BATCH_JOB_ID, SEQUENCE_NUMBER);
DROP SEQUENCE cpf.cpf_bjeg_seq;
