package ca.bc.gov.open.cpf.api.domain;

public interface ConfigProperty {
  String COMPONENT_NAME = "COMPONENT_NAME";

  String CONFIG_PROPERTY = "/CPF/CPF_CONFIG_PROPERTIES";

  String DEFAULT = "default";

  String ENVIRONMENT_NAME = "ENVIRONMENT_NAME";

  String MODULE_BEAN_PROPERTY = "MODULE_BEAN_PROPERTY";

  String MODULE_CONFIG = "MODULE_CONFIG";

  String MODULE_NAME = "MODULE_NAME";

  String PROPERTY_NAME = "PROPERTY_NAME";

  String PROPERTY_VALUE = "PROPERTY_VALUE";

  String PROPERTY_VALUE_TYPE = "PROPERTY_VALUE_TYPE";

  String GLOBAL = "GLOBAL";
}
